# Generated by Django 4.2.2 on 2023-06-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.timestamp')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('blogs.timestamp',),
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.timestamp')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=('blogs.timestamp',),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.timestamp')),
                ('credentials', models.TextField(help_text='json format')),
                ('platform', models.CharField(max_length=70)),
                ('page', models.CharField(blank=True, max_length=70, null=True)),
                ('is_baned', models.BooleanField(default=False)),
            ],
            bases=('blogs.timestamp',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.timestamp')),
                ('title_seo', models.CharField(max_length=100)),
                ('description_seo', models.CharField(blank=True, max_length=400, null=True)),
                ('h1', models.CharField(db_index=True, max_length=120)),
                ('h2', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('alt', models.TextField(blank=True, null=True)),
                ('href', models.TextField(blank=True, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_copyrighted', models.BooleanField(default=False)),
                ('is_reeled', models.BooleanField(default=False)),
                ('reel_path', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.category')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.lang')),
                ('parent_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
                ('social_media', models.ManyToManyField(to='blogs.socialmedia')),
            ],
            bases=('blogs.timestamp',),
        ),
    ]
