# Generated by Django 4.2.2 on 2023-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='h2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
