# Generated by Django 4.2.2 on 2023-06-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blog_h2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='deepl_lang',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
