# Generated by Django 4.2.2 on 2023-06-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='checked_for_copyright',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
