# Generated by Django 4.2.2 on 2023-06-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_checked_for_copyright_blog_translated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogs.timestamp')),
                ('token', models.TextField()),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('epochTime', models.TextField()),
            ],
            bases=('blogs.timestamp',),
        ),
    ]
