# Generated by Django 4.2.2 on 2023-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='h1',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='h2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
