# Generated by Django 4.2.2 on 2023-06-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_h1_alter_blog_h2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_seo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='h1',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='h2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_seo',
            field=models.CharField(max_length=500),
        ),
    ]
