# Generated by Django 4.2.2 on 2023-07-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blog_description_seo_alter_blog_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_splitted',
            field=models.BooleanField(default=False),
        ),
    ]
